### ISSUE TITLE
New files after compile

### ISSUE THREAD

**Issue by daimor** [doublefint/vscode-cos#17]
when I compile file this extension creates a new file for this class, and it does not care if have another point of view how I would like to store files. I have folders for packages and files for classes, and it just ignores my structure and creates files with the full name of the class, outside of packages folders.

**Comment by doublefint** [comment]
Hi, daimor! :) Do you use options "cos.export.folder" and/or "cos.export.atelier" ?

**Comment by daimor** [comment]
All settings by default.
only ip, port,and namespace configured.

**Comment by doublefint** [comment]
By default option "cos.export.atelier" is off and extension used "flat" name conversion logic. Please, enable it and check again.

**Comment by daimor** [comment]
Why it does use original file name all the time, without any options?
