### ISSUE TITLE
Please get this extension tagged in Marketplace as deprecated

### ISSUE THREAD

**Issue by gjsjohnmurray** [doublefint/vscode-cos#46]
See https://github.com/microsoft/vscode/issues/150005#issuecomment-1132636317

When VS Code 1.68 ships next month it is expected to include a new capability which steers users away from deprecated extensions. This feature is already previewing in Insiders.

@doublefint please contact @isidorn to get this one tagged and redirect people to intersystems-community.vscode-objectscript

pinging @daimor @isc-bsaviano @isc-rsingh

**Comment by isidorn** [comment]
You can also just confirm here you would like us to mark it as deprecated.

@gjsjohnmurray thanks for driving this.

**Comment by doublefint** [comment]
@gjsjohnmurray @isidorn 
I apologize for the delay in reply. 
Yes, I fully agree that this extension should be marked as deprecated
It is also desirable to redirect people to intersystems-community.vscode-objectscript

**Comment by isidorn** [comment]
Done.
Feel free to close this issue. It should be marked as deprecated in Insiders from tomorrow. You can try it out.
Thanks

**Comment by isc-rsingh** [comment]
Thank you @doublefint and @isidorn!

**Comment by gjsjohnmurray** [comment]
> It should be marked as deprecated in Insiders from tomorrow. You can try it out.

@isidorn I'm not seeing the warning triangle and greyed-out entry that other deprecated extensions such as Bracket Pair Colorizer 2 display:

![image](https://user-images.githubusercontent.com/6726799/170228550-ab9557ca-d043-4675-a2f3-1b0359f7e52e.png)

**Comment by isidorn** [comment]
@gjsjohnmurray thanks for the ping, we need to do another update on our side which I was unaware off. I expect this to show up by tomorrow.

**Comment by gjsjohnmurray** [comment]
@isidorn no sign of it yet.

![image](https://user-images.githubusercontent.com/6726799/170454267-894d732f-7338-4a46-89f6-f6ab0c9732ea.png)

Is the extra update in Insiders, or does it need to happen on Marketplace? Or somewhere else?

**Comment by isidorn** [comment]
Somewhere else. I still have not deployed that yet, doing it now. Sorry about that!

**Comment by isidorn** [comment]
I have just now ran the pipeline, so I expect this extension to be marked as deprecated in a couple of hours. Thank you!

**Comment by gjsjohnmurray** [comment]
Confirmed.

![image](https://user-images.githubusercontent.com/6726799/170485162-49e419f9-91b9-40b4-9075-487cb11e9ae2.png)

Thanks @isidorn

**Comment by isidorn** [comment]
Awesome, thanks!
