### ISSUE TITLE
Tag list in marketplace

### ISSUE THREAD

**Issue by daimor** [doublefint/vscode-cos#9]
Что за интересный набор тегов по которым предлагется искать этот плагин в marketplace?
![image](https://user-images.githubusercontent.com/1212251/32881261-f8b83ffa-cab0-11e7-957b-510715ea93a8.png)
cacheobjectscript так не находит
зачем в тегах COS.INC, и keybindings
почему нет тега intersystems, это первое как я пытался найти плагин для установки. пришлось искать на community ссылку в marketplace. Здесь в readme тоже бы наверно было бы хорошо дать ссылку на marketplace.

**Comment by doublefint** [comment]
Дима, привет! 
Marketplace навешивает теги самостоятельно, основываясь на id, или других элементах, из package.json
Спасибо, что обратил внимание, подумаю что с этим можно сделать
